### ISSUE TITLE
"cm->values[i][target_idx]" is not locked in the function add_to_cm

### ISSUE THREAD

**Issue by Repairman-ST** [cloudflare/rakelimit#17]
A little confused：Why is "cm->values[i][target_idx]" not locked in the function add_to_cm? Thanks

**Comment by lmb** [comment]
Hi!

It's not locked since we're worried about contention from multiple CPUs. During an attack this could lead to significant wastage of resources. So instead we accept that the algorithm is racy, and can miscount packets. See #16 for a mitigation (but not a fix).

Off topic: please don't put your question into the title of the issue. It means I have to go and edit it so that it's searchable from the issue tracker.

**Comment by Repairman-ST** [comment]
thank you very much
